### ISSUE TITLE
Instructions of this software

### ISSUE THREAD

**Issue by lyhbuaa** [dnilsson1/G-codeToRapid#1]
Thank you for your work. Please allow me to ask if you have the instructions of this software. I can't open the link of your paper

**Comment by dnilsson1** [comment]
@lyhbuaa
OK, that is strange. The link seems to work just fine for me. 
If you give me your email I can send you the paper. However in order to get the code to work you need to update some of the pcsdk functions. Please check ABB developer enter for the pcsdk reference manual.

**Comment by lyhbuaa** [comment]
Thank you very much for your kind reply. My email is lyh_buaa@aliyun.com

**Comment by dnilsson1** [comment]
The Readme section has been updated

**Comment by lyhbuaa** [comment]
Thank you very much！

**Comment by dnilsson1** [comment]
You are welcome! Please consider giving the repo a star if you enjoy it 🌟
